### ISSUE TITLE
VIA software continues  to say "Searching for devices"

### ISSUE THREAD

**Issue by halfpint415** [WestBerryVIA/via-releases#3]
![initial screen](https://github.com/WestBerryVIA/via-releases/assets/159068288/d2247584-e738-43ac-aa65-04390669921a)

I have the other 2 json files, but the keyboard page on VIA does not detect the keyboard so I am unable to upload the files to map my keyboard.

Thanks!

**Comment by ffdez** [comment]
I have the same problem. How do you solve it?

**Comment by Jefferderp** [comment]
Settings > Show Design Tab > Click on Design Tab > Load JSON > Back to Configure tab

Not intuitive and took a few tries before it worked.
